#! /bin/node

let olt_ip = process.argv[2];
let comunity = process.argv[3];

const fh = require('snmp-fiberhome');

const options = {
    ip: olt_ip,
    community: comunity,
    port: 161,
    trapPort: 162,
    enableWarnings: true,
    enableLogs: true
}

let c = 1;
fh.getAuthorizedOnus(options).then(onuList => {
    onuList.forEach(element => {
        console.log(`${c} => ${element._onuIndex} => ${element.macAddress}`)
        c++;
    });
})